version: '3.8'

services:

  backend:
    build: ./back-end
    command: uvicorn main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 6969

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend